name: age_calculator_lamda
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter: 
    sdk: flutter
  get_cli: ^1.7.1
  month_calculator: ^0.1.4
  animated_flip_counter: ^0.2.2

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "G:/git repository/CPAD-Gazipur/Age-Calculator-Lambda/icons/Screenshot (467).png"
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

